version: '3.7'

services:
  printscript-ui:
    container_name: 'printscript-ui'
    image: 'ghcr.io/ingsis-team/ingsis-printscript-ui:latest'
    pull_policy: always
    expose:
      - "80"

  snippet-api:
    container_name: 'snippet-api'
    image: 'ghcr.io/ingsis-team/ingsis-snippet-service:latest'
    pull_policy: always
    expose:
      - "8089"
    depends_on:
      - snippet-db
    environment:
      DB_HOST: snippet-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      PERMISSION_URL: ${PERMISSION_URL}
      ASSET_URL: ${ASSET_URL}
      PRINTSCRIPT_URL: ${PRINTSCRIPT_URL}
      AUTH0_SERVER_URI: ${AUTH0_SERVER_URI}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}

  snippet-db:
    container_name: 'snippet-db'
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_SNIPPET_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SNIPPET_PASSWORD}
      POSTGRES_DB: ${POSTGRES_SNIPPET_DB}
    ports:
      - "${DB_SNIPPET_PORT}:${DB_SNIPPET_PORT}"
    volumes:
      - snippet_volume:/var/lib/postgresql/data

  permission-db:
    container_name: 'permission-db'
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_PERMISSION_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PERMISSION_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PERMISSION_DB}
    ports:
      - "${DB_PERMISSION_PORT}:5432"
    volumes:
      - permission_volume:/var/lib/postgresql/data

  permission-api:
    container_name: 'permission-api'
    image: 'ghcr.io/ingsis-team/ingsis-permission-service:latest'
    environment:
      DB_USER: ${POSTGRES_PERMISSION_USER}
      DB_PASSWORD: ${POSTGRES_PERMISSION_PASSWORD}
      DB_NAME: ${POSTGRES_PERMISSION_DB}
      DB_HOST: permission-db
      DB_PORT: ${DB_PERMISSION_PORT}
      PERMISSION_URL: ${PERMISSION_URL}
    depends_on:
      - permission-db

  printscript-api:
    container_name: 'printscript-api'
    image: 'ghcr.io/ingsis-team/ingsis-printscript-service:latest'
    pull_policy: always
    depends_on:
      - printscript-db
      - redis

  printscript-db:
    container_name: 'printscript-db'
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_PRINTSCRIPT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PRINTSCRIPT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PRINTSCRIPT_DB}

  redis:
    container_name: 'redis'
    image: redis:6-alpine

  api-manager:
    container_name: "asset-service"
    image: "ghcr.io/austral-ingsis/snippet-asset-service:latest"
    environment:
      AZURE_HOST: "http://azurite"

  reverse-proxy:
    container_name: 'reverse-proxy-dev'
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - snippet-api
      - permission-api
      - printscript-ui
#      - printscript-api
      - api-manager
      - snippet-db
      - permission-db
#      - printscript-db

  duckdns:
    image: lscr.io/linuxserver/duckdns:version-d63af1c1
    container_name: duckdns
    environment:
      - SUBDOMAINS=ingsis
      - TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped

  azurite-manager:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

volumes:
  snippet_volume:
  permission_volume:
